name: Deploy Nitpick Snap-in

on:
  pull_request:
    types: [closed]
    paths:
      - 'snap-in/**'

jobs:
  create-marketplace-submission:
    name: Create marketplace submission
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Create marketplace submission
        uses: devrev/github-actions/create-marketplace-submission@create-marketplace-submission-v0.1.12
        with:
          code_ref_url: ${{ github.event.pull_request.url }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          read_actions_token: ${{ secrets.READ_GITHUB_ACTIONS_RELEASES }}
        env:
          DEVREV_PAT: ${{ secrets.DEVREV_DEV_PAT }}
